### ISSUE TITLE
Simulations with ideal bandpasses

### ISSUE THREAD

**Issue by zonca** [simonsobs/map_based_simulations#12]
For the next TOD simulation, we would like to use top-hat bandpasses.
All the map based simulations we have are delta-bandpass, I would like to run:

* high resolution foregrounds with fixed spectral index
* high resolution foregrounds with variable spectral index
* extragalactic

with top-hat bandpasses.

2 questions:

* what figures should I use for bandwidth?
* how do we define flat bandpasses? There is a discussion on the CMB-S4 wiki: https://cmb-s4.org/wiki/index.php/Bandpass_Convention_-_What_does_flat_mean , they actually recommend `nu^-2`

**Comment by mhasself** [comment]
On the first question, please go through @smsimon and the pwg:exm group (they are supposed to track the use of such parameters).

On the second question, I think I disagree with the consensus reached on that S4 page.  The purpose of going from delta function bands to non-zero bandwidth is fully achieved by having almost _any_ bandpass function with realistic width, because the point is just to make sure that you can handle the fact that different spectra pick-up differently across the band.  The added realism of modeling idealized feed response (nu^-2) is, if I understand it, completely uninteresting.

Furthermore, saying that the bandpass is "top hat", and then defining that bandpass as nu^-2, seems like obfuscation.  When we say "top hat", we conventionally mean a function that is 0, then 1 for a while, then 0.  With the nu^-2 weight included in the definition of top-hat, if someone asks what the central frequency of the band-pass is, you have to say, "uh, what frequency?" because even if you've "centered" your top hat at nu_0, i.e. it's a band that's 0 except for inside [nu_0 - delta/2, nu_0 + delta/2]... the centroid (and thus plausibly the central frequency) is... and forgive-me-if-I-get-this-wrong-even-if-it-supports-my-point-to-do-so, ...:

  ln( (nu + delta) / (nu - delta) ) * (nu^2 - delta^2) / 2 delta.

Blech.

**Comment by zonca** [comment]
thanks @mhasself would you do a top-hat response in `K_RJ` or in `K_CMB`?

**Comment by smsimon** [comment]
@zonca The bandpasses are here: http://simonsobservatory.wikidot.com/detbandpasses
The bolded designs are the final designs.

**Comment by zonca** [comment]
Thanks @smsimon, I should do the weighting in `K_RJ`, right?

**Comment by mhasself** [comment]
@smsimon I'd like the top-hat approximations to the real bands to be "owned" by exm.  So whatever the results are, let's make sure they're tracked on the exm page (and referenced by sim groups).

@zonca I think the right weighting is in spectral radiance (SR), a.k.a. "SR" or Jy/sr.  The K_RJ has a pesky nu^2 (but not the same nu^2 as before) in the conversion to I_nu.

**Comment by zonca** [comment]
@smsimon to provide a table of bandwidths

**Comment by zonca** [comment]
ok, @smsimon produced a table of center frequencies and bandwidths, @keskitalo suggested they should go into `sotodlib`, anyone volunteers to create a pull request to `sotodlib` for those? Or point me where they should go.

I can then import `sotodlib` from `mapsims` to run the map based simulations.

**Comment by smsimon** [comment]
@zonca done

**Comment by zonca** [comment]
very good thanks, reference: https://github.com/simonsobs/sotodlib/pull/22
I have everything I need to proceed with this.

**Comment by zonca** [comment]
results available, see https://github.com/simonsobs/map_based_simulations/pull/19
